// TEMPORARY DATA

export let role = "admin";

export const usersData = [
  {
    id: 1,
    userId: "1234567890",
    userName: "Fırat Salmanoğlu",
    firstName: "Fırat",
    lastName: "Salmanoğlu",
    bloodType: "ARh+",
    birthday: "01/01/2000",
    sex: "Erkek",
    organizationName: "Ege University",
    role: ["Admin"],
    email: "john@doe.com",
    photo: "/avatar.png",
    phoneNumber: "1234567890",
    registrationDate: "10/06/2024",
    address: "Bornova. İzmir",
  },
  {
    id: 2,
    userId: "1234567890",
    userName: "Fırat Salmanoğlu",
    firstName: "Fırat",
    lastName: "Salmanoğlu",
    bloodType: "ARh+",
    birthday: "01/01/2000",
    sex: "Erkek",
    organizationName: "Ege University",
    role: ["Admin"],
    email: "john@doe.com",
    photo: "/avatar.png",
    phoneNumber: "1234567890",
    registrationDate: "10/06/2024",
    address: "Bornova. İzmir",
  },
  {
    id: 3,
    userId: "1234567890",
    userName: "Fırat Salmanoğlu",
    firstName: "Fırat",
    lastName: "Salmanoğlu",
    bloodType: "ARh+",
    birthday: "01/01/2000",
    sex: "Erkek",
    organizationName: "Ege University",
    role: ["Admin"],
    email: "john@doe.com",
    photo: "/avatar.png",
    phoneNumber: "1234567890",
    registrationDate: "10/06/2024",
    address: "Bornova. İzmir",
  },
  {
    id: 4,
    userId: "1234567890",
    userName: "Fırat Salmanoğlu",
    firstName: "Fırat",
    lastName: "Salmanoğlu",
    bloodType: "ARh+",
    birthday: "01/01/2000",
    sex: "Erkek",
    organizationName: "Ege University",
    role: ["Admin"],
    email: "john@doe.com",
    photo: "/avatar.png",
    phoneNumber: "1234567890",
    registrationDate: "10/06/2024",
    address: "Bornova. İzmir",
  },
  {
    id: 5,
    userId: "1234567890",
    userName: "Fırat Salmanoğlu",
    firstName: "Fırat",
    lastName: "Salmanoğlu",
    bloodType: "ARh+",
    birthday: "01/01/2000",
    sex: "Erkek",
    organizationName: "Ege University",
    role: ["Admin"],
    email: "john@doe.com",
    photo: "/avatar.png",
    phoneNumber: "1234567890",
    registrationDate: "10/06/2024",
    address: "Bornova. İzmir",
  },
  {
    id: 6,
    userId: "1234567890",
    userName: "Fırat Salmanoğlu",
    firstName: "Fırat",
    lastName: "Salmanoğlu",
    bloodType: "ARh+",
    birthday: "01/01/2000",
    sex: "Erkek",
    organizationName: "Ege University",
    role: ["Admin"],
    email: "john@doe.com",
    photo: "/avatar.png",
    phoneNumber: "1234567890",
    registrationDate: "10/06/2024",
    address: "Bornova. İzmir",
  },
  {
    id: 7,
    userId: "1234567890",
    userName: "Fırat Salmanoğlu",
    firstName: "Fırat",
    lastName: "Salmanoğlu",
    bloodType: "ARh+",
    birthday: "01/01/2000",
    sex: "Erkek",
    organizationName: "Ege University",
    role: ["Admin"],
    email: "john@doe.com",
    photo: "/avatar.png",
    phoneNumber: "1234567890",
    registrationDate: "10/06/2024",
    address: "Bornova. İzmir",
  },
  {
    id: 8,
    userId: "1234567890",
    userName: "Fırat Salmanoğlu",
    firstName: "Fırat",
    lastName: "Salmanoğlu",
    bloodType: "ARh+",
    birthday: "01/01/2000",
    sex: "Erkek",
    organizationName: "Ege University",
    role: ["Admin"],
    email: "john@doe.com",
    photo: "/avatar.png",
    phoneNumber: "1234567890",
    registrationDate: "10/06/2024",
    address: "Bornova. İzmir",
  },
  {
    id: 9,
    userId: "1234567890",
    userName: "Fırat Salmanoğlu",
    firstName: "Fırat",
    lastName: "Salmanoğlu",
    bloodType: "ARh+",
    birthday: "01/01/2000",
    sex: "Erkek",
    organizationName: "Ege University",
    role: ["Admin"],
    email: "john@doe.com",
    photo: "/avatar.png",
    phoneNumber: "1234567890",
    registrationDate: "10/06/2024",
    address: "Bornova. İzmir",
  },
  {
    id: 10,
    userId: "1234567890",
    userName: "Fırat Salmanoğlu",
    firstName: "Fırat",
    lastName: "Salmanoğlu",
    bloodType: "ARh+",
    birthday: "01/01/2000",
    sex: "Erkek",
    organizationName: "Ege University",
    role: ["Admin"],
    email: "john@doe.com",
    photo: "/avatar.png",
    phoneNumber: "1234567890",
    registrationDate: "10/06/2024",
    address: "Bornova. İzmir",
  },
];

export const devicesData = [
  {
    id: 1,
    extinguisherID: "1234567890",
    ownerID:"75",
    owner:"XXXX Hospital",
    address: "Bornova İzmir",
    serialNumber:"95958478784",
    deviceType: "Yangın Tüpü",
    feature: "CO2",
    respPersonID: ["105", "215"],
    respPerson: ["Ayhan Uğur","Fırat Salmanoğlu"],
    manufactureDate: "25/10/2024",
    expiryDate: "25/10/2025",
    lastInspectionDate: "25/06/2024",
    location: "roof",
    statuss: "OK",
    photo:"/avatar.png",

  },
  {
    id: 2,
    extinguisherID: "1234567890",
    ownerID:"75",
    owner:"XXXX Hospital",
    address: "Bornova İzmir",
    serialNumber:"95958478784",
    deviceType: "Yangın Tüpü",
    feature: "CO2",
    respPersonID: ["105", "215"],
    respPerson: ["Ayhan Uğur","Fırat Salmanoğlu"],
    manufactureDate: "25/10/2024",
    expiryDate: "25/10/2025",
    lastInspectionDate: "25/06/2024",
    location: "roof",
    statuss: "OK",
    photo:"/avatar.png",
  },
  {
    id: 3,
    extinguisherID: "1234567890",
    ownerID:"75",
    owner:"XXXX Hospital",
    address: "Bornova İzmir",
    serialNumber:"95958478784",
    deviceType: "Yangın Tüpü",
    feature: "CO2",
    respPersonID: ["105", "215"],
    respPerson: ["Ayhan Uğur","Fırat Salmanoğlu"],
    manufactureDate: "25/10/2024",
    expiryDate: "25/10/2025",
    lastInspectionDate: "25/06/2024",
    location: "roof",
    statuss: "OK",
    photo:"/avatar.png",
  },
  {
    id: 4,
    extinguisherID: "1234567890",
    ownerID:"75",
    owner:"XXXX Hospital",
    address: "Bornova İzmir",
    serialNumber:"95958478784",
    deviceType: "Yangın Tüpü",
    feature: "CO2",
    respPersonID: ["105", "215"],
    respPerson: ["Ayhan Uğur","Fırat Salmanoğlu"],
    manufactureDate: "25/10/2024",
    expiryDate: "25/10/2025",
    lastInspectionDate: "25/06/2024",
    location: "roof",
    statuss: "OK",
    photo:"/avatar.png",
  },
  {
    id: 5,
    extinguisherID: "1234567890",
    ownerID:"75",
    owner:"XXXX Hospital",
    address: "Bornova İzmir",
    serialNumber:"95958478784",
    deviceType: "Yangın Tüpü",
    feature: "CO2",
    respPersonID: ["105", "215"],
    respPerson: ["Ayhan Uğur","Fırat Salmanoğlu"],
    manufactureDate: "25/10/2024",
    expiryDate: "25/10/2025",
    lastInspectionDate: "25/06/2024",
    location: "roof",
    statuss: "OK",
    photo:"/avatar.png",
  },
  {
    id: 6,
    extinguisherID: "1234567890",
    ownerID:"75",
    owner:"XXXX Hospital",
    address: "Bornova İzmir",
    serialNumber:"95958478784",
    deviceType: "Yangın Tüpü",
    feature: "CO2",
    respPersonID: ["105", "215"],
    respPerson: ["Ayhan Uğur","Fırat Salmanoğlu"],
    manufactureDate: "25/10/2024",
    expiryDate: "25/10/2025",
    lastInspectionDate: "25/06/2024",
    location: "roof",
    statuss: "OK",
    photo:"/avatar.png",
  },
  {
    id: 7,
    extinguisherID: "1234567890",
    ownerID:"75",
    owner:"XXXX Hospital",
    address: "Bornova İzmir",
    serialNumber:"95958478784",
    deviceType: "Yangın Tüpü",
    feature: "CO2",
    respPersonID: ["105", "215"],
    respPerson: ["Ayhan Uğur","Fırat Salmanoğlu"],
    manufactureDate: "25/10/2024",
    expiryDate: "25/10/2025",
    lastInspectionDate: "25/06/2024",
    location: "roof",
    statuss: "OK",
    photo:"/avatar.png",
  },
  {
    id: 8,
    extinguisherID: "1234567890",
    ownerID:"75",
    owner:"XXXX Hospital",
    address: "Bornova İzmir",
    serialNumber:"95958478784",
    deviceType: "Yangın Tüpü",
    feature: "CO2",
    respPersonID: ["105", "215"],
    respPerson: ["Ayhan Uğur","Fırat Salmanoğlu"],
    manufactureDate: "25/10/2024",
    expiryDate: "25/10/2025",
    lastInspectionDate: "25/06/2024",
    location: "roof",
    statuss: "OK",
    photo:"/avatar.png",
  },
  {
    id: 9,
    extinguisherID: "1234567890",
    ownerID:"75",
    owner:"XXXX Hospital",
    address: "Bornova İzmir",
    serialNumber:"95958478784",
    deviceType: "Yangın Tüpü",
    feature: "CO2",
    respPersonID: ["105", "215"],
    respPerson: ["Ayhan Uğur","Fırat Salmanoğlu"],
    manufactureDate: "25/10/2024",
    expiryDate: "25/10/2025",
    lastInspectionDate: "25/06/2024",
    location: "roof",
    statuss: "OK",
    photo:"/avatar.png",
  },
  {
    id: 10,
    extinguisherID: "1234567890",
    ownerID:"75",
    owner:"XXXX Hospital",
    address: "Bornova İzmir",
    serialNumber:"95958478784",
    deviceType: "Yangın Tüpü",
    feature: "CO2",
    respPersonID: ["105", "215"],
    respPerson: ["Ayhan Uğur","Fırat Salmanoğlu"],
    manufactureDate: "25/10/2024",
    expiryDate: "25/10/2025",
    lastInspectionDate: "25/06/2024",
    location: "roof",
    statuss: "OK",
    photo:"/avatar.png",
  },
];

export const offersData = [
  {
    id: 1,
    offerID: "101",
    providerID: "001",
    providerName: "XXX Yangın Ltd.",
    ownerID: "138",
    ownerName: "ZZZ Gıda Tekn. Ltd.",
    offerDate: "12/12/2023",
    amount: "126.9000,00",
    servicesOffered: ["Değişim", "Bakım"],
    status: "OK",
    expiryDate: "25/10/2025",
  },
  {
    id: 2,
    offerID: "101",
    providerID: "001",
    providerName: "XXX Yangın Ltd.",
    ownerID: "138",
    ownerName: "ZZZ Gıda Tekn. Ltd.",
    offerDate: "12/12/2023",
    amount: "126.9000,00",
    servicesOffered: ["Değişim", "Bakım"],
    status: "OK",
    expiryDate: "25/10/2025",
  },
  {
    id: 3,
    offerID: "101",
    providerID: "001",
    providerName: "XXX Yangın Ltd.",
    ownerID: "138",
    ownerName: "ZZZ Gıda Tekn. Ltd.",
    offerDate: "12/12/2023",
    amount: "126.9000,00",
    servicesOffered: ["Değişim", "Bakım"],
    status: "OK",
    expiryDate: "25/10/2025",
  },
  {
    id: 4,
    offerID: "101",
    providerID: "001",
    providerName: "XXX Yangın Ltd.",
    ownerID: "138",
    ownerName: "ZZZ Gıda Tekn. Ltd.",
    offerDate: "12/12/2023",
    amount: "126.9000,00",
    servicesOffered: ["Değişim", "Bakım"],
    status: "OK",
    expiryDate: "25/10/2025",
  },
  {
    id: 5,
    offerID: "101",
    providerID: "001",
    providerName: "XXX Yangın Ltd.",
    ownerID: "138",
    ownerName: "ZZZ Gıda Tekn. Ltd.",
    offerDate: "12/12/2023",
    amount: "126.9000,00",
    servicesOffered: ["Değişim", "Bakım"],
    status: "OK",
    expiryDate: "25/10/2025",
  },
  {
    id: 6,
    offerID: "101",
    providerID: "001",
    providerName: "XXX Yangın Ltd.",
    ownerID: "138",
    ownerName: "ZZZ Gıda Tekn. Ltd.",
    offerDate: "12/12/2023",
    amount: "126.9000,00",
    servicesOffered: ["Değişim", "Bakım"],
    status: "OK",
    expiryDate: "25/10/2025",
  },
  {
    id: 7,
    offerID: "101",
    providerID: "001",
    providerName: "XXX Yangın Ltd.",
    ownerID: "138",
    ownerName: "ZZZ Gıda Tekn. Ltd.",
    offerDate: "12/12/2023",
    amount: "126.9000,00",
    servicesOffered: ["Değişim", "Bakım"],
    status: "OK",
    expiryDate: "25/10/2025",
  },
  {
    id: 8,
    offerID: "101",
    providerID: "001",
    providerName: "XXX Yangın Ltd.",
    ownerID: "138",
    ownerName: "ZZZ Gıda Tekn. Ltd.",
    offerDate: "12/12/2023",
    amount: "126.9000,00",
    servicesOffered: ["Değişim", "Bakım"],
    status: "OK",
    expiryDate: "25/10/2025",
  },
  {
    id: 9,
    offerID: "101",
    providerID: "001",
    providerName: "XXX Yangın Ltd.",
    ownerID: "138",
    ownerName: "ZZZ Gıda Tekn. Ltd.",
    offerDate: "12/12/2023",
    amount: "126.9000,00",
    servicesOffered: ["Değişim", "Bakım"],
    status: "OK",
    expiryDate: "25/10/2025",
  },
  {
    id: 10,
    offerID: "101",
    providerID: "001",
    providerName: "XXX Yangın Ltd.",
    ownerID: "138",
    ownerName: "ZZZ Gıda Tekn. Ltd.",
    offerDate: "12/12/2023",
    amount: "126.9000,00",
    servicesOffered: ["Değişim", "Bakım"],
    status: "OK",
    expiryDate: "25/10/2025",
  },
];

export const maintenancesData = [
  {
    id: 1,
    recordID: "005",
    deviceSerialNumber: "125487",
    performedByID: "196587",
    performedByName: "Ayhan Uğur",
    instPerformed:"KSKS Yangın Güvenlik Ltd.",
    instServed: "AAA Tarım Sanayi A.Ş.",
    maintenanceDate: "13/07/2023",
    maintenanceType: "Bakım",
    details: "Basınçlar kontrol edildi",
    nexyMaintenanceDate: "13/07/2024",
    status: "OK",
  },
  {
    id: 2,
    recordID: "005",
    deviceSerialNumber: "125487",
    performedByID: "196587",
    performedByName: "Ayhan Uğur",
    instPerformed:"KSKS Yangın Güvenlik Ltd.",
    instServed: "AAA Tarım Sanayi A.Ş.",
    maintenanceDate: "13/07/2023",
    maintenanceType: "Bakım",
    details: "Basınçlar kontrol edildi",
    nexyMaintenanceDate: "13/07/2024",
    status: "OK",
  },
  {
    id: 3,
    recordID: "005",
    deviceSerialNumber: "125487",
    performedByID: "196587",
    performedByName: "Ayhan Uğur",
    instPerformed:"KSKS Yangın Güvenlik Ltd.",
    instServed: "AAA Tarım Sanayi A.Ş.",
    maintenanceDate: "13/07/2023",
    maintenanceType: "Bakım",
    details: "Basınçlar kontrol edildi",
    nexyMaintenanceDate: "13/07/2024",
    status: "OK",
  },
  {
    id: 4,
    recordID: "005",
    deviceSerialNumber: "125487",
    performedByID: "196587",
    performedByName: "Ayhan Uğur",
    instPerformed:"KSKS Yangın Güvenlik Ltd.",
    instServed: "AAA Tarım Sanayi A.Ş.",
    maintenanceDate: "13/07/2023",
    maintenanceType: "Bakım",
    details: "Basınçlar kontrol edildi",
    nexyMaintenanceDate: "13/07/2024",
    status: "OK",
  },
  {
    id: 5,
    recordID: "005",
    deviceSerialNumber: "125487",
    performedByID: "196587",
    performedByName: "Ayhan Uğur",
    instPerformed:"KSKS Yangın Güvenlik Ltd.",
    instServed: "AAA Tarım Sanayi A.Ş.",
    maintenanceDate: "13/07/2023",
    maintenanceType: "Bakım",
    details: "Basınçlar kontrol edildi",
    nexyMaintenanceDate: "13/07/2024",
    status: "OK",
  },
  {
    id: 6,
    recordID: "005",
    deviceSerialNumber: "125487",
    performedByID: "196587",
    performedByName: "Ayhan Uğur",
    instPerformed:"KSKS Yangın Güvenlik Ltd.",
    instServed: "AAA Tarım Sanayi A.Ş.",
    maintenanceDate: "13/07/2023",
    maintenanceType: "Bakım",
    details: "Basınçlar kontrol edildi",
    nexyMaintenanceDate: "13/07/2024",
    status: "OK",
  },
  {
    id: 7,
    recordID: "005",
    deviceSerialNumber: "125487",
    performedByID: "196587",
    performedByName: "Ayhan Uğur",
    instPerformed:"KSKS Yangın Güvenlik Ltd.",
    instServed: "AAA Tarım Sanayi A.Ş.",
    maintenanceDate: "13/07/2023",
    maintenanceType: "Bakım",
    details: "Basınçlar kontrol edildi",
    nexyMaintenanceDate: "13/07/2024",
    status: "OK",
  },
  {
    id: 8,
    recordID: "005",
    deviceSerialNumber: "125487",
    performedByID: "196587",
    performedByName: "Ayhan Uğur",
    instPerformed:"KSKS Yangın Güvenlik Ltd.",
    instServed: "AAA Tarım Sanayi A.Ş.",
    maintenanceDate: "13/07/2023",
    maintenanceType: "Bakım",
    details: "Basınçlar kontrol edildi",
    nexyMaintenanceDate: "13/07/2024",
    status: "OK",
  },
  {
    id: 9,
    recordID: "005",
    deviceSerialNumber: "125487",
    performedByID: "196587",
    performedByName: "Ayhan Uğur",
    instPerformed:"KSKS Yangın Güvenlik Ltd.",
    instServed: "AAA Tarım Sanayi A.Ş.",
    maintenanceDate: "13/07/2023",
    maintenanceType: "Bakım",
    details: "Basınçlar kontrol edildi",
    nexyMaintenanceDate: "13/07/2024",
    status: "OK",
  },
  {
    id: 10,
    recordID: "005",
    deviceSerialNumber: "125487",
    performedByID: "196587",
    performedByName: "Ayhan Uğur",
    instPerformed:"KSKS Yangın Güvenlik Ltd.",
    instServed: "AAA Tarım Sanayi A.Ş.",
    maintenanceDate: "13/07/2023",
    maintenanceType: "Bakım",
    details: "Basınçlar kontrol edildi",
    nexyMaintenanceDate: "13/07/2024",
    status: "OK",
  },
];

export const notificationsData = [
  {
    id: 1,
    notificationID: "889",
    userID: "007",
    userName: "Serkan Korkmaz",
    organizationName: "AAA Yangın Hizmetleri A.Ş",
    deviceSerialNumber: "445689",
    deviceOwner: "BBG Hayvancılık A.Ş.",
    message: "xxxx nolu cihazın bakım tarihi yaklaşıyor...",
    notificationDate: "24/10/2024",
    isRead: "Okundu",
    notificationType: "Hatırlatma",
  },
  {
    id: 2,
    notificationID: "889",
    userID: "007",
    userName: "Serkan Korkmaz",
    organizationName: "AAA Yangın Hizmetleri A.Ş",
    deviceSerialNumber: "445689",
    deviceOwner: "BBG Hayvancılık A.Ş.",
    message: "xxxx nolu cihazın bakım tarihi yaklaşıyor...",
    notificationDate: "24/10/2024",
    isRead: "Okundu",
    notificationType: "Hatırlatma",
  },
  {
    id: 3,
    notificationID: "889",
    userID: "007",    
    userName: "Serkan Korkmaz",
    organizationName: "AAA Yangın Hizmetleri A.Ş",
    deviceSerialNumber: "445689",
    deviceOwner: "BBG Hayvancılık A.Ş.",
    message: "xxxx nolu cihazın bakım tarihi yaklaşıyor...",
    notificationDate: "24/10/2024",
    isRead: "Okundu",
    notificationType: "Hatırlatma",
  },
  {
    id: 4,
    notificationID: "889",
    userID: "007",
    userName: "Serkan Korkmaz",
    organizationName: "AAA Yangın Hizmetleri A.Ş",
    deviceSerialNumber: "445689",
    deviceOwner: "BBG Hayvancılık A.Ş.",
    message: "xxxx nolu cihazın bakım tarihi yaklaşıyor...",
    notificationDate: "24/10/2024",
    isRead: "Okundu",
    notificationType: "Hatırlatma",
  },
  {
    id: 5,
    notificationID: "889",
    userID: "007",
    userName: "Serkan Korkmaz",
    organizationName: "AAA Yangın Hizmetleri A.Ş",
    deviceSerialNumber: "445689",
    deviceOwner: "BBG Hayvancılık A.Ş.",
    message: "xxxx nolu cihazın bakım tarihi yaklaşıyor...",
    notificationDate: "24/10/2024",
    isRead: "Okundu",
    notificationType: "Hatırlatma",
  },
  {
    id: 5,
    notificationID: "889",
    userID: "007",
    userName: "Serkan Korkmaz",
    organizationName: "AAA Yangın Hizmetleri A.Ş",
    deviceSerialNumber: "445689",
    deviceOwner: "BBG Hayvancılık A.Ş.",
    message: "xxxx nolu cihazın bakım tarihi yaklaşıyor...",
    notificationDate: "24/10/2024",
    isRead: "Okundu",
    notificationType: "Hatırlatma",
  },
  {
    id: 7,
    notificationID: "889",
    userID: "007",
    userName: "Serkan Korkmaz",
    organizationName: "AAA Yangın Hizmetleri A.Ş",
    deviceSerialNumber: "445689",
    deviceOwner: "BBG Hayvancılık A.Ş.",
    message: "xxxx nolu cihazın bakım tarihi yaklaşıyor...",
    notificationDate: "24/10/2024",
    isRead: "Okundu",
    notificationType: "Hatırlatma",
  },
  {
    id: 8,
    notificationID: "889",
    userID: "007",
    userName: "Serkan Korkmaz",
    organizationName: "AAA Yangın Hizmetleri A.Ş",
    deviceSerialNumber: "445689",
    deviceOwner: "BBG Hayvancılık A.Ş.",
    message: "xxxx nolu cihazın bakım tarihi yaklaşıyor...",
    notificationDate: "24/10/2024",
    isRead: "Okundu",
    notificationType: "Hatırlatma",
  },
  {
    id: 9,
    notificationID: "889",
    userID: "007",
    userName: "Serkan Korkmaz",
    organizationName: "AAA Yangın Hizmetleri A.Ş",
    deviceSerialNumber: "445689",
    deviceOwner: "BBG Hayvancılık A.Ş.",
    message: "xxxx nolu cihazın bakım tarihi yaklaşıyor...",
    notificationDate: "24/10/2024",
    isRead: "Okundu",
    notificationType: "Hatırlatma",
  },
  {
    id: 10,
    notificationID: "889",
    userID: "007",
    userName: "Serkan Korkmaz",
    organizationName: "AAA Yangın Hizmetleri A.Ş",
    deviceSerialNumber: "445689",
    deviceOwner: "BBG Hayvancılık A.Ş.",
    message: "xxxx nolu cihazın bakım tarihi yaklaşıyor...",
    notificationDate: "24/10/2024",
    isRead: "Okundu",
    notificationType: "Hatırlatma",
  },
];

export const lessonsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Tommy Wise",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Rhoda Frank",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Della Dunn",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Bruce Rodriguez",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Birdie Butler",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Bettie Oliver",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Herman Howard",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Lucinda Thomas",
  },
  {
    id: 9,
    subject: "Physics",
    class: "6C",
    teacher: "Ronald Roberts",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "4B",
    teacher: "Julia Pittman",
  },
];

export const examsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Martha Morris",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Randall Garcia",
    date: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Myrtie Scott",
    date: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Alvin Swanson",
    date: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Mabelle Wallace",
    date: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Dale Thompson",
    date: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Allie Conner",
    date: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Hunter Fuller",
    date: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Lois Lindsey",
    date: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Vera Soto",
    date: "2025-01-01",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Anthony Boone",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Clifford Bowen",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Catherine Malone",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Willie Medina",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Jose Ruiz",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Katharine Owens",
    dueDate: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Shawn Norman",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Don Holloway",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Franklin Gregory",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Danny Nguyen",
    dueDate: "2025-01-01",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Fırat Salmanoğlu",
    student: "Fırat Salmanoğlu",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Fırat Salmanoğlu",
    student: "Fırat Salmanoğlu",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Fırat Salmanoğlu",
    student: "Fırat Salmanoğlu",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Fırat Salmanoğlu",
    student: "Fırat Salmanoğlu",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Fırat Salmanoğlu",
    student: "Fırat Salmanoğlu",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Fırat Salmanoğlu",
    student: "Fırat Salmanoğlu",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Fırat Salmanoğlu",
    student: "Fırat Salmanoğlu",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Fırat Salmanoğlu",
    student: "Fırat Salmanoğlu",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Fırat Salmanoğlu",
    student: "Fırat Salmanoğlu",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Fırat Salmanoğlu",
    student: "Fırat Salmanoğlu",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Lake Trip",
    class: "1A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Picnic",
    class: "2A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Beach Trip",
    class: "3A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Museum Trip",
    class: "4A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Music Concert",
    class: "5A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Magician Show",
    class: "1B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "Lake Trip",
    class: "2B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Cycling Race",
    class: "3B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Art Exhibition",
    class: "4B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "Sports Tournament",
    class: "5B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "About 4A Math Test",
    class: "4A",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "About 3A Math Test",
    class: "3A",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "About 3B Math Test",
    class: "3B",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "About 6A Math Test",
    class: "6A",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "About 8C Math Test",
    class: "8C",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "About 2A Math Test",
    class: "2A",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "About 4C Math Test",
    class: "4C",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "About 4B Math Test",
    class: "4B",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "About 3C Math Test",
    class: "3C",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "About 1C Math Test",
    class: "1C",
    date: "2025-01-01",
  },
];


// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
export const calendarEvents = [
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 7, 12, 8, 0),
    end: new Date(2024, 7, 12, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 12, 9, 0),
    end: new Date(2024, 7, 12, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 12, 10, 0),
    end: new Date(2024, 7, 12, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 7, 12, 11, 0),
    end: new Date(2024, 7, 12, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2024, 7, 12, 13, 0),
    end: new Date(2024, 7, 12, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 12, 14, 0),
    end: new Date(2024, 7, 12, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 13, 9, 0),
    end: new Date(2024, 7, 13, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 13, 10, 0),
    end: new Date(2024, 7, 13, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 7, 13, 11, 0),
    end: new Date(2024, 7, 13, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 13, 14, 0),
    end: new Date(2024, 7, 13, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 7, 14, 8, 0),
    end: new Date(2024, 7, 14, 8, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 14, 10, 0),
    end: new Date(2024, 7, 14, 10, 45),
  },

  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2024, 7, 14, 13, 0),
    end: new Date(2024, 7, 14, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 14, 14, 0),
    end: new Date(2024, 7, 13, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 15, 9, 0),
    end: new Date(2024, 7, 15, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 15, 10, 0),
    end: new Date(2024, 7, 15, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 7, 15, 11, 0),
    end: new Date(2024, 7, 15, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 15, 14, 0),
    end: new Date(2024, 7, 15, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 7, 16, 8, 0),
    end: new Date(2024, 7, 16, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 16, 9, 0),
    end: new Date(2024, 7, 16, 9, 45),
  },

  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 7, 16, 11, 0),
    end: new Date(2024, 7, 16, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2024, 7, 16, 13, 0),
    end: new Date(2024, 7, 16, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 16, 14, 0),
    end: new Date(2024, 7, 16, 14, 45),
  },
];